### PR TITLE
Fix bug with `"every token inside"`

### LINKED ISSUE #1806: "last token inside" refers to tokens outside when there is only one token
```
"aaa"
```

`"take last token inside air"` selects the trailing `"`, not `aaa`. Similarly for first token. `take every token inside` is also entertaining.

Pretty sure this is a bug.

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
Fixes #1806

## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [/] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [/] I have not broken the cheatsheet

### CODE REVIEW

File: packages/cursorless-engine/src/processTargets/modifiers/EveryScopeStage.ts [hunk 1]
```diff
@@ -61,7 +61,8 @@ export class EveryScopeStage implements ModifierStage {
 
       if (
         scopes.length === 1 &&
-        scopes[0].domain.contains(target.contentRange)
+        scopes[0].domain.contains(target.contentRange) &&
+        !target.hasExplicitScopeType
```
Comment (phillco) [inline packages/cursorless-engine/src/processTargets/modifiers/EveryScopeStage.ts:65]: hats + this are implicit, others are explicit

**Review by phillco — APPROVED** [review]
