### PR TITLE
Surrounding pairs: Fall back to text based algorithm when error node is detected.

### LINKED ISSUE #712: Surrounding pair problem in error python code
`def funk(words:list<str>):`
`take pair` in `<str>` doesn't work

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
Fixes #712

## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [ ] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [ ] I have not broken the cheatsheet

### CODE REVIEW

File: packages/cursorless-engine/src/processTargets/modifiers/surroundingPair/index.ts [hunk 1]
```diff
@@ -148,3 +160,22 @@ function processSurroundingPairCore(
     scopeType,
   );
 }
+
+function nodeHasError(node: SyntaxNode, includeChildren = false): boolean {
```
Comment (pokey) [inline packages/cursorless-engine/src/processTargets/modifiers/surroundingPair/index.ts:164]: This seems quite conservative. Are there test cases that fail if you don't eg check grand-siblings?

Comment (AndreasArvidsson) [reply packages/cursorless-engine/src/processTargets/modifiers/surroundingPair/index.ts:164]: The added test for example. The error node is a child to an ancestor of the selected node.

Comment (pokey) [reply packages/cursorless-engine/src/processTargets/modifiers/surroundingPair/index.ts:164]: as discussed, let's use your proposed version for now and if it becomes bothersome we can revisit.  see also #1600

**Review by pokey — APPROVED** [review]
