### PR TITLE
Fix handling of hierarchical scopes

### LINKED ISSUE #1308: "chuck X lines" chucks X-1 lines if first target line is empty
If you have....
```
a

b
```
Then "chuck <X> lines" will chuck X-1 lines if the first line is empty.  So "chuck 2 lines row 2" will only delete line 2 (the blank line after 'a').  I'm not entirely confident, but I think it only the first line matters whether it is empty.

"chuck <X> lines" should chuck X lines regardless of if the top line is empty.

### LINKED ISSUE #1317: Rework scope handlers in preparation for hierarchical tree-sitter scopes
- Only step over smallest scope starting at position
- Figure out how to properly handle containing
- [x] https://github.com/cursorless-dev/cursorless/issues/1308
- Preparation for https://github.com/cursorless-dev/cursorless/pull/629

### LINKED ISSUE #1424: Rework how modifiers handle hierarchical scopes
Writing #629 revealed some deficiencies in the way we handle hierarchical scopes.  Here are some test cases that should pass:

https://github.com/cursorless-dev/cursorless/compare/main...pokey%2Ftag%2Fbroken-hierarchical-scope-test-cases

- [ ] Make sure all these test cases are capturing desired behaviour, not existing buggy behaviour. I believe I left a few in that capture today's broken behaviour
- [ ] Change spoken forms / test names to use stock "last" / "previous" instead of "final" / "last"
- [ ] The "every state" test relies on https://github.com/cursorless-dev/cursorless/pull/1432

### PR DESCRIPTION
**Pull request by pokey**
- Closes #1424
- Closes #1308
- Closes #1317

## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [ ] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [ ] I have not broken the cheatsheet

### CODE REVIEW

File: packages/cursorless-engine/src/processTargets/modifiers/getPreferredScopeTouchingPosition.ts [hunk 1]
```diff
@@ -44,28 +38,13 @@ export function getPreferredScopeTouchingPosition(
...
-      // If we've found a scope that strictly contains position,
-      // then we're not going to find any more minimal scopes
-      break;
-    }
-  }
+  const candidates: TargetScope[] = Array.from(
+    scopeHandler.generateScopes(editor, position, "forward", {
+      containment: "required",
+      allowAdjacentScopes: true,
+      maxAncestorIndex: 0,
```
Comment (pokey) [inline packages/cursorless-engine/src/processTargets/modifiers/getPreferredScopeTouchingPosition.ts:45]: All of the logic we had here is now performed by `BaseScopeHandler` if `maxAncestorIndex` is 0

File: packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/BaseScopeHandler.ts [hunk 2]
```diff
@@ -104,21 +105,52 @@ export default abstract class BaseScopeHandler implements ScopeHandler {
     let previousScope: TargetScope | undefined = undefined;
     const hints: ScopeIteratorRequirements = {
       ...DEFAULT_REQUIREMENTS,
+      distalPosition:
+        requirements.distalPosition ?? direction === "forward"
+          ? editor.document.range.end
+          : editor.document.range.start,
```
Comment (pokey) [inline packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/BaseScopeHandler.ts:111]: Setting distal position to be the end of the document simplifies lots of code, as that's logically what we were doing anyway

File: packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/BaseTreeSitterScopeHandler.ts
Comment (pokey) [inline packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/TreeSitterScopeHandler/BaseTreeSitterScopeHandler.ts:1]: this file is an example of how using end of file instead of `null` for `distalPosition` results in cleaner code

File: packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/shouldYieldScope.ts [hunk 3]
```diff
@@ -55,50 +64,34 @@ export function shouldYieldScope(
...
-      ? domain.end.isEqual(position)
-      : domain.start.isEqual(position))
-  ) {
-    return false;
-  }
+  return partiallyContains(
+    new Range(position, distalPosition),
+    domain,
+    allowAdjacentScopes,
+  );
```
Comment (pokey) [inline packages/cursorless-engine/src/processTargets/modifiers/scopeHandlers/shouldYieldScope.ts:71]: switching `distalPosition` to end of doc dramatically simplifies this code, and fixes several bugs along the way

File: packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/relativeScopes/clearOneToken.yml [hunk 4]
```diff
@@ -19,4 +19,8 @@ initialState:
       active: {line: 0, character: 13}
   marks: {}
 fullTargets: [{type: primitive, mark: {type: cursor}, modifiers: [{type: relativeScope, scopeType: {type: token}, offset: 0, length: 1, direction: forward}]}]
-thrownError: {name: TooFewScopesError}
+finalState:
+  documentContents: aaa bbb  ddd eee fff
+  selections:
+    - anchor: {line: 0, character: 8}
+      active: {line: 0, character: 8}
```
Comment (pokey) [inline packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/relativeScopes/clearOneToken.yml:26]: I don't really see the point of raising an error if the input target contains too many scopes.  Seems reasonable to just yield starting from the beginning and if we don't reach the end who cares 🤷‍♂️

**Review by AndreasArvidsson — APPROVED** [review]
