### PR TITLE
Fix focus editor in changes working tree

### LINKED ISSUE #819: Can't set selection in the source/changes working tree
The function [focusEditor](https://github.com/cursorless-dev/cursorless/blob/bc24adcb984fd0da6845985a8ecff4982884fcf7/src/util/setSelectionsAndFocusEditor.ts#L53-L66) dost not work when `editor.viewColumn` is null

Cursorless throws the following error message `Couldn't find notebook editor for given document`

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
Fixes #819

## Checklist

- [ ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)

### CODE REVIEW

File: src/util/setSelectionsAndFocusEditor.ts [hunk 1]
```diff
@@ -65,6 +68,26 @@ export async function focusEditor(editor: TextEditor) {
...
+  if (editor.viewColumn != null) {
+    return editor.viewColumn;
+  }
+  // TODO: tabGroups is not available on older versions of vscode we still support.
+  // Remove any cast as soon as version is updated.
+  if (semver.lt(version, "1.67.0")) {
+    return undefined;
+  }
+  const viewColumn: ViewColumn | undefined = (window as any)?.tabGroups
+    ?.activeTabGroup?.viewColumn;
```
Comment (pokey) [inline src/util/setSelectionsAndFocusEditor.ts:81]: Why are you using the view column of the active tab group? Shouldn't you look for the tab group containing `editor`?

Comment (AndreasArvidsson) [reply src/util/setSelectionsAndFocusEditor.ts:81]: As far as I can tell that information is not available on each tab. I have to dig deeper in the api and see if I can find that data.

Comment (AndreasArvidsson) [reply src/util/setSelectionsAndFocusEditor.ts]: There is no editor or document on the tab groups, but I managed to find a uri

File: src/util/setSelectionsAndFocusEditor.ts [hunk 2]
```diff
@@ -78,21 +78,10 @@ function getViewColumn(editor: TextEditor): ViewColumn | undefined {
     return undefined;
   }
   const uri = editor.document.uri.toString();
-  const tabGroups: any[] = (window as any)?.tabGroups?.all ?? [];
-  const tabGroup = tabGroups.find(
-    (tabGroup: any) =>
-      !!tabGroup?.tabs.find(
-        (tab: any) => tab?.input?.modified?.toString() === uri
-      )
+  const tabGroup = (window as any)?.tabGroups?.all?.find((tabGroup: any) =>
```
Comment (pokey) [inline src/util/setSelectionsAndFocusEditor.ts:81]: Do we need all these `?.`s?

File: src/util/setSelectionsAndFocusEditor.ts [hunk 3]
```diff
@@ -78,21 +78,10 @@ function getViewColumn(editor: TextEditor): ViewColumn | undefined {
...
+    tabGroup?.tabs.find((tab: any) => tab?.input?.modified?.toString() === uri)
```
Comment (pokey) [inline src/util/setSelectionsAndFocusEditor.ts:82]: I think we prob want to support `original` and `uri` in addition to `modified`

**Review by pokey — COMMENTED** [review]
Looks good with a couple comments

File: src/util/setSelectionsAndFocusEditor.ts (hunk 2 above)
Comment (AndreasArvidsson) [reply src/util/setSelectionsAndFocusEditor.ts:81]: Probably not but since it's untyped I think it's better to be safe than sorry.

File: src/util/setSelectionsAndFocusEditor.ts (hunk 3 above)
Comment (AndreasArvidsson) [reply src/util/setSelectionsAndFocusEditor.ts:82]: I decided to leave them out. Since original and modified is in the same tab focusing that tab would always focus the modified editor for some reason. I think it's a better behavior to throw an error than to focus the wrong editor. Including uri only gave us false positives like notebooks and I haven't found a use case where it's needed.

**Review by pokey — APPROVED** [review]
